# Generated by Django 3.0.4 on 2020-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeleave',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Reason', models.CharField(max_length=100)),
                ('leave_date', models.DateField()),
            ],
        ),
    ]
